### ISSUE TITLE
Too much role checkers?

### ISSUE THREAD

**Issue by sung1asses** [designatedcoder/admin_o_matic#2]
With role/permissions controll you add middlewares on routes/web.php, also added to controller constructor, and also you check role on every method in that controller. What is the point?)

**Comment by harri4007** [comment]
This is code from a  tutorial series on YouTube.  I've given multiple options on how to set up the middleware so that you can pick and choose which are appropriate for your needs.  You do not have to use all of them.

**Comment by designatedcoder** [comment]
This is code from a tutorial series on YouTube. I've given multiple options on how to set up the middleware so that you can pick and choose which are appropriate for your needs. You do not have to use all of them.

**Comment by sung1asses** [comment]
Will you continue this tutorial?)))

**Comment by designatedcoder** [comment]
> Will you continue this tutorial?)))

The project was finished weeks ago.  Here's the intro episode.  Have a look: 
https://youtu.be/1L8B7pGOBdc
