### ISSUE TITLE
error on img logo and user

### ISSUE THREAD

**Issue by diorz38** [designatedcoder/admin_o_matic#5]
i just did a little fix there, in SideBar.vue file, to this:
```
<div class="image">
    <img :src="$page.props.user.profile_photo_url" class="img-circle elevation-2" alt="User Image">
</div>

```
after change jetstream config to enable Features::profilePhotos()
and i make some little tweak id AppLayout, so if user is admin menu dashboard can go directly to admin dashboard:
```
<ul class="navbar-nav mr-auto">
    <div v-if="$page.props.user.is_admin === '1'">
        <jet-nav-link :href="route('admin.dashboard.index')">
            Dashboard
        </jet-nav-link>
    </div>
    <div v-else>
    <jet-nav-link
        :href="route('dashboard')"
        :active="route().current('dashboard')"
    >
        Dashboard
    </jet-nav-link>
    </div>
</ul>
```

**Comment by designatedcoder** [comment]
Hey there dior, thanks for contributing that.  It's not really an error/bug for this demo project, I only used images from AdminLTE. You are correct for implementing this in your version.
